### ISSUE TITLE
Tooltips broken on some AA items, calling non-existent asset

### ISSUE THREAD

**Issue by Azure-Fang** [Kherae/Automation-Aides#2]
[17:48:58.354] [Error] Could not load image asset '/interface/tooltips/bodytall.png', using placeholder default.
(AssetException) No such asset '/interface/tooltips/bodytall.png'

Confirmed affected items:
Storage Bridge
Item Transference Device

**Comment by Kherae** [comment]
https://github.com/Kherae/Automation-Aides/commit/94d78d070d0596fe2a5bbca87d5163cb20a37326 I really should have looked closer when copyin things over. was too slepy.
